export type AudioAlertType = 'file' | 'none'

export interface AudioConfig {
  type: AudioAlertType
  fileName?: string  // file in /audio/ directory
}

export type SystemStatus = 'normal' | 'warning' | 'critical' | 'offline'

export type SystemType = 'equipment' | 'ups' | 'sensor'

export type AlarmSeverity = 'warning' | 'critical' | 'offline'

export type TrendDirection = 'up' | 'down' | 'stable'

export type MetricItemType = 'inputVoltage' | 'outputVoltage' | 'batteryVoltage' | 'inputCurrent' | 'outputCurrent' | 'batteryCurrent' | 'inputFrequency' | 'outputFrequency' | 'load' | 'temperature' | 'status' | 'batteryRemaining' | 'custom'

// Sound client (TMS SoundSense) selected via LAN auto-discovery. Stored inside
// EquipmentConfig so the facility can be re-identified and re-provisioned later.
export interface SoundClientInfo {
  kind?: 'sound' | 'ping'
  discoveryPort?: number
  serverIp?: string
  id: string            // stable UUID generated by the client on first run
  name: string          // operator-entered 장비명 on the client
  host: string          // Windows computer name
  ip: string            // last known IPv4 address
  mac?: string
  ver?: string
  provisionedAt?: string
}

// A client that answered a discovery probe (see docs/sound-client-protocol.md)
export interface DiscoveredClient {
  kind?: 'sound' | 'ping'
  discoveryPort?: number
  alarm?: boolean | null
  running?: boolean
  id: string
  name: string
  host: string
  ip: string
  serverIp: string      // local address of the interface that heard the reply
  mac: string
  ver: string
  target: { ip: string; port: number } | null
  muted: boolean
  sound: boolean
  uptimeSec: number
  registered: { systemId: string; systemName: string } | null
}

// Equipment config: pattern-based status detection
export interface EquipmentConfig {
  normalPatterns: string[]
  criticalPatterns: string[]
  matchMode: 'exact'
  client?: SoundClientInfo
  // Consecutive critical messages before a fault is raised; unset = 1 (alarm on the
  // first message). Only noisy analogue senders raise it. See src/lib/equipment-alarm.ts.
  criticalConfirmations?: number
}

// Condition-based threshold types (for sensor)
export type ConditionOperator = 'between' | 'gte' | 'lte' | 'eq' | 'neq'

export interface ThresholdCondition {
  operator: ConditionOperator
  value1: number          // between: lower bound, gte/lte: threshold value
  value2: number | null   // between: upper bound, others: null
  stringValue?: string    // eq/neq: text-based comparison (status type)
}

export interface StatusConditions {
  normal: ThresholdCondition[]
  critical: ThresholdCondition[]
  coldCritical: ThresholdCondition[]  // cold warning (temperature only, critical level)
  dryCritical: ThresholdCondition[]   // dry warning (humidity only, critical level)
  humidCritical: ThresholdCondition[] // humid warning (humidity only, critical level)
}

export type DataMatchOperator = 'contains' | 'startsWith' | 'endsWith' | 'equals' | 'regex'

export interface DataMatchCondition {
  operator: DataMatchOperator
  value: string
}

// Display item for UPS/sensor metrics
export interface DisplayItem {
  name: string
  index: number
  unit: string
  itemType?: MetricItemType
  warning: number | null       // UPS: 하한치 (lower limit), alarm if value <= this
  critical: number | null      // UPS: 상한치 (upper limit), alarm if value >= this
  chartEnabled?: boolean       // DEPRECATED, kept for backward compat read
  chartGroup?: string | null   // UPS: free-form chart group name (e.g. '입력전압', 'R상', '배터리') | null
  alarmEnabled?: boolean       // UPS: enable alarm for this metric (default true)
  conditions?: StatusConditions  // sensor condition mode (if present, use conditions instead of warning/critical)
  audioConfig?: AudioConfig      // per-item audio alert (sensor only)
  dataMatchConditions?: DataMatchCondition[]  // data matching filter (sensor only)
}

// UPS/Sensor config: delimiter-based parsing with multiple metrics
export interface MetricsConfig {
  delimiter: string
  displayItems: DisplayItem[]
  customCode?: string
}

// Union type for system config
export type SystemConfig = EquipmentConfig | MetricsConfig

export interface System {
  id: string
  name: string
  type: SystemType
  status: SystemStatus
  isActive: boolean
  isEnabled: boolean
  port: number | null
  protocol: string | null
  lastDataAt: Date | null
  config: string | null
  audioConfig: string | null
  createdAt: Date
  updatedAt: Date
  metrics?: Metric[]
  alarms?: Alarm[]
}

export interface Metric {
  id: string
  systemId: string
  name: string
  value: number
  textValue?: string | null
  unit: string
  min: number | null
  max: number | null
  warningThreshold: number | null
  criticalThreshold: number | null
  trend: TrendDirection | null
  createdAt: Date
  updatedAt: Date
}

export interface Alarm {
  id: string
  systemId: string
  severity: AlarmSeverity
  message: string
  value: string | null
  acknowledged: boolean
  acknowledgedAt: Date | null
  acknowledgedBy: string | null
  createdAt: Date
  resolvedAt: Date | null
  system?: System
}

export interface Setting {
  id: string
  key: string
  value: string
  category: string | null
  createdAt: Date
  updatedAt: Date
}

// Prisma-compatible types (string-based for database compatibility)
export interface PrismaSystem {
  id: string
  name: string
  type: string
  status: string
  isActive: boolean
  isEnabled: boolean
  port: number | null
  protocol: string | null
  topic: string | null
  lastDataAt: Date | null
  offlineThreshold: number | null
  encoding: string | null
  config: string | null
  audioConfig: string | null
  createdAt: Date
  updatedAt: Date
  metrics?: PrismaMetric[]
  alarms?: PrismaAlarm[]
}

export interface PrismaMetric {
  id: string
  systemId: string
  name: string
  value: number
  textValue?: string | null
  unit: string
  min: number | null
  max: number | null
  warningThreshold: number | null
  criticalThreshold: number | null
  trend: string | null
  createdAt: Date
  updatedAt: Date
}

export interface PrismaAlarm {
  id: string
  systemId: string
  severity: string
  message: string
  value: string | null
  acknowledged: boolean
  acknowledgedAt: Date | null
  acknowledgedBy: string | null
  createdAt: Date
  resolvedAt: Date | null
  occurrenceCount?: number
  firstSeenAt?: Date
  lastSeenAt?: Date
  system?: PrismaSystem
}

// 항공기상청 웹 자료 기반 뇌전 감시 + WING 현장 확인 (공항 특보는 별도 제공하지 않음)
export interface Wing15Item {
  key: string
  kind: 'strikes'
  title: string
  startAt: string
  endAt: string | null
  // 마지막 낙뢰 후 1시간 이내 (경보 진행 중)
  active: boolean
  strikeCount?: number
  // 표시된 낙뢰가 모두 WING에서 확인됨
  confirmed: boolean
}

export interface Wing15Checklist {
  special: boolean
  maintenance: boolean
  // Signature of the unconfirmed alert set the checklist belongs to; a new
  // alert set invalidates previously checked boxes.
  sig: string
}

export interface Wing15State {
  ok: boolean
  error?: string
  updatedAt: string
  observedAt?: string
  sig: string
  items: Wing15Item[]
  checklist: Wing15Checklist
}

// WebSocket message types
export type WebSocketMessageType = 'metric' | 'alarm' | 'alarm-resolved' | 'system' | 'init' | 'ping' | 'delete' | 'raw' | 'siren-sync' | 'settings' | 'systems-changed' | 'wing15'

export interface WebSocketMessage {
  type: WebSocketMessageType
  data: {
    systemId?: string
    systemName?: string
    status?: SystemStatus
    // For metrics
    metricId?: string
    metricName?: string
    value?: number
    textValue?: string | null
    unit?: string
    trend?: TrendDirection | null
    // For alarms
    alarmId?: string
    alarmIds?: string[]
    severity?: AlarmSeverity
    message?: string
    alarmValue?: string | null
    acknowledged?: boolean
    bulk?: boolean
    // For raw data preview
    port?: number
    rawData?: string
    // For settings sync
    audioEnabled?: string
    serverAudioEnabled?: string
    muteEndTime?: string
    temperatureEnabled?: string
    upsEnabled?: string
    gateEnabled?: string
    wing15Enabled?: string
    // For wing15 lightning monitor
    wing15?: Wing15State
  }
  timestamp: string
}
