// An OEM installer is optional private build input, never a repository asset.
import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const generated = path.join(root, 'src-tauri/windows/generated');
mkdirSync(generated, { recursive: true });
const oem = process.env.TMS_NPCAP_OEM_INSTALLER;
let include = '; Generated by scripts/build-setup.mjs.\n';
if (oem) {
  const source = path.resolve(oem);
  execFileSync('powershell.exe', ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-File',
    path.join(root, 'src-tauri/windows/install-network.ps1'), '-Action', 'Verify', '-Installer', source], { stdio: 'inherit' });
  const bytes = readFileSync(source);
  const hash = createHash('sha256').update(bytes).digest('hex');
  cpSync(source, path.join(generated, 'npcap-oem.exe'));
  include += `!define TMS_NPCAP_OEM\n!define TMS_NPCAP_HASH "${hash}"\n`;
}
// Always overwrite this file so a previous OEM build cannot leak into a standard build.
writeFileSync(path.join(generated, 'npcap.nsh'), include);
execFileSync('cargo', ['tauri', 'build', '--bundles', 'nsis'], { cwd: root, stdio: 'inherit' });
const conf = JSON.parse(readFileSync(path.join(root, 'src-tauri/tauri.conf.json'), 'utf8'));
const release = path.join(root, 'src-tauri/target/release');
const setup = path.join(release, 'bundle/nsis', `${conf.productName}_${conf.version}_x64-setup.exe`);
if (!existsSync(setup)) throw new Error(`설치 파일을 찾을 수 없습니다: ${setup}`);
cpSync(setup, path.join(release, 'tms-ping-monitor-setup.exe'));
writeFileSync(path.join(release, 'setup-manifest.json'), JSON.stringify({
  version: conf.version, npcap: oem ? 'bundled-oem' : 'official-download',
  sha256: createHash('sha256').update(readFileSync(setup)).digest('hex'),
}, null, 2));
console.log(`Setup: ${setup} (Npcap: ${oem ? 'OEM 내장' : '설치 중 공식 다운로드'})`);
