// Build a self-contained internal-use installer. Driver binaries never enter Git.
import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const generated = path.join(root, 'src-tauri/windows/generated');
mkdirSync(generated, { recursive: true });
const oem = process.env.TMS_NPCAP_OEM_INSTALLER;
const source = oem ? path.resolve(oem) : path.join(root, '.cache/npcap-1.89.exe');
const freeHash = '8aed85e900d783d1308506e919587d3e540451947af8a82f2d04f819e44305cc';
if (!existsSync(source) && !oem) {
  mkdirSync(path.dirname(source), { recursive: true });
  const response = await fetch('https://npcap.com/dist/npcap-1.89.exe', { signal: AbortSignal.timeout(120_000) });
  if (!response.ok) throw new Error(`Npcap 다운로드 실패: HTTP ${response.status}`);
  writeFileSync(source, Buffer.from(await response.arrayBuffer()));
}
const bytes = readFileSync(source);
const hash = createHash('sha256').update(bytes).digest('hex');
if (!oem && hash !== freeHash) throw new Error('Npcap 설치 파일의 SHA-256이 일치하지 않습니다.');
execFileSync('powershell.exe', ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-File',
  path.join(root, 'src-tauri/windows/install-network.ps1'), '-Action', 'Verify', '-Installer', source,
  '-ExpectedHash', hash], { stdio: 'inherit' });
cpSync(source, path.join(generated, 'npcap-installer.exe'));
// Always overwrite the selection so a previous OEM build cannot leak into the next build.
writeFileSync(path.join(generated, 'npcap.nsh'),
  `; Generated by scripts/build-setup.mjs.\n!define TMS_NPCAP_HASH "${hash}"\n${oem ? '!define TMS_NPCAP_OEM\n' : ''}`);
execFileSync('cargo', ['tauri', 'build', '--bundles', 'nsis'], { cwd: root, stdio: 'inherit' });
const conf = JSON.parse(readFileSync(path.join(root, 'src-tauri/tauri.conf.json'), 'utf8'));
const release = path.join(root, 'src-tauri/target/release');
const setup = path.join(release, 'bundle/nsis', `${conf.productName}_${conf.version}_x64-setup.exe`);
if (!existsSync(setup)) throw new Error(`설치 파일을 찾을 수 없습니다: ${setup}`);
cpSync(setup, path.join(release, 'tms-ping-monitor-setup.exe'));
writeFileSync(path.join(release, 'setup-manifest.json'), JSON.stringify({
  version: conf.version, npcap: oem ? 'bundled-oem' : 'bundled-free', offline: true,
  sha256: createHash('sha256').update(readFileSync(setup)).digest('hex'),
}, null, 2));
console.log(`폐쇄망용 Setup: ${setup} (Npcap ${oem ? 'OEM' : '무료판'} + WebView2 내장)`);
